name: release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go 1.21
        uses: actions/setup-go@v1
        with:
          go-version: 1.21
        id: go

      - name: Set Envs
        run: |
          echo GO_VERSION=$(go version | awk '{print $3;}') >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          GO_VERSION: ${{ env.GITHUB_GO_VERSION }}

      - name: Refresh Proxy Go Package
        run: |
          echo "Repository name: ${{ github.repository }}"
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag name: $TAG_NAME"
          curl -v https://proxy.golang.org/${{ github.repository }}/goctlx/@v/$TAG_NAME.info